offsetParam:
  name: offset
  in: query
  schema:
    type: integer
    minimum: 0
  description: The number of items to skip before returning the results

limitParam:
  in: query
  name: limit
  schema:
    type: integer
    format: int32
    minimum: 1
    maximum: 100
    default: 20
  description: The number of items to return
